Проект "Карты подскажут" готов
dmitrykoryanov/karty-podskazhut pull request #1
Opened 2024-11-28 17:48 UTC by dmitrykoryanov

2024-11-28 20:10 UTC, Avaakum requested changes
Развернуть общий комментарий ⬇︎

Доброго времени суток. У вас получилась хорошая работа!

_Что понравилось:_

- работают темы
- отличная структура файлов проекта
- Хорошая семантика
- Хорошие стили 
- Отзывчивая верстка
- Похоже на макет на брейк-поинтах


_Что необходимо исправить:_


- **Все комментарии, кроме комментариев с пометками «Можно лучше» и «Отлично». А так же не забудьте проверить, есть ли свёрнутые комментарии, которые обычно находятся по центру страницы с ревью при прокрутке вниз, и выглядят следующим образом https://disk.yandex.ru/i/FyX-8tzeqLjimw**

- Некорректный цвет фона при светлой теме
- https://disk.yandex.ru/i/zqqK4OrFD4L6aA не сброшен стандартный фокус/не присвоен видимый фокус для ссылок
- Для ссылок нужно присвоить ховер из макета. Подчёркивание должно быть с прозрачностью при ховере
- https://disk.yandex.ru/i/6U6U0-1tj4GOWQ сверьте размер буквицы при всех ширинах


- https://disk.yandex.ru/i/B4cfnQ9bedRdkQ  Маркеры списка должны находится по центру  напротив элемента списка, а не по верхней строке. Для этого нужно опустить вниз буллит на  50% элемента списка, например с помощью  inset-block-start и затем поднять его на половину собственной высоты(7.5px) с помощью margin-block-start. 



- При ширине экрана 1440px _не совпадает с макетом_:
   -  https://disk.yandex.ru/i/DYyMPc12j2AeXQ отступ над списком

- При ширине экрана 360px _не совпадает с макетом_:
  - https://disk.yandex.ru/i/29Vo0MvQYiLvlQ есть несоответствия макету, сверяйте размеры с заданием, начиная с размеров буквицы
  - https://disk.yandex.ru/i/hTZnAa-8vWh9ig

-   **В проекте есть недочёты в отображении по макету, контролируйте самостоятельно с помощью PixelPerfect перед следующей итерацией:**
    - 	Для более точного контроля отображения вёрстки можно воспользоваться [расширением PixelPerfect](https://chrome.google.com/webstore/detail/perfectpixel-by-welldonec/dkaagdgjmgdmbnecmcefdhjekcoceebi  )  для `Chrome`, для этого в фигме выделить весь макет, экспортировать его картинкой и наложить на вёрстку в браузере. Плагин позволяет наложить изображение на вёрстку в браузере, тем самым можно с легкостью подправить недочёты по отображению. А так же, если включить в расширении инверсию цвета и прозрачность 50%, то соответствие по пикселям и цветам видно лучше, так как при сложении цветов получается однородный серый цвет.

- https://disk.yandex.ru/i/Pi1V3yOFfVCZOQ от 360px и более ширины экрана страница прокручивается по горизонтали
   - Для некоторых элементов нужно поменять стили. Для устранения горизонтального скролла часто применяют подобный подход: можно прямо в Dev Tools(или через IDE) по одной скрывать секции и смотреть когда он пропадает, и потом добавляют по одной устраняя скролл на всех разрешениях.  Плюс можно добавить например красный бордер(или аутлайн) для всех элементов(селектор для всех элементов со стилей `* {outline: 1px red solid; }`, можно добавить в файл стилей) и посмотреть что вылезает. А так же можно еще раз просмотреть уроки с платформы, где тоже есть много полезных советов. 
    - _Скролл нужно убирать без св-ва overflow, нужно подправить верстку на тех интервалах ширина экрана, где это необходимо_


_Что можно улучшить:_

- Все комментарии с пометкой "Можно лучше"
- Для всех функций ` var() ` в CSS нужно задать резервные значения,  на случай если доступ к кастомному свойству по имени будет невозможен. 
- Можно использовать атрибуты `target="_blank"` для ссылок на сторонние ресурсы для того чтобы пользователю не приходилось заново открывать сайт проекта
- больше использовать currentColor, где это возможно
- больше использовать vi вместо vw


Желаю успеха!

2024-11-28 20:10 UTC, Avaakum commented on styles/style.css
> +.header__theme-toggler {
У списка не сброшен пэддинг по умолчанию.

---

Обратите внимание, что у  списков следует убирать стандартные стили браузера(для селекторов классов этих списоков): `margin`, `padding`, `list-style-type`

2024-11-28 20:10 UTC, Avaakum commented on styles/style.css
> +.colored-text {
Этот элемент нужно сделать строчно-блочным, что бы он корректно переносился на мобильном разрешении.

2024-11-28 20:10 UTC, Avaakum commented on styles/style.css
> +  font-family: var(--accent-font), sans-serif;
Это шрифт с засечками, используйте тип serif для фолбэка

2024-11-28 20:10 UTC, Avaakum commented on styles/style.css
> +li::before {
Это плохая практика использовать тег для конкретной стилизации. Всегда может быть добавлен ещё список с другим поведением. Используйте класс элемента или составной селектор с классом родительского контейнера.

2024-11-28 20:10 UTC, Avaakum commented on index.html
> +    <div class="header__logo">
---

**Можно лучше:**

Логотип должен быть ссылкой **без атрибута href,**(что бы по ссылке не было перехода). А так же, что бы при навигации с клавиатуры этот элемент не получал видимый фокус. **Пустой атрибут href тоже нужно удалить.**

2024-11-28 20:10 UTC, Avaakum commented on index.html
> +      <source srcset="images/cards-1x.avif" type="image/avif">
Так как у нас по 2 изображения каждого типа(формата), используйте вместо 2х source один с записью источников изображений с одним форматом, но разной плотностью пикселей и с указанием этой плотности пикселей. 

Пример ` <source srcset="640x480.png 1x, 1280x960.png 2x"> ` 

Дополнительно https://doka.guide/html/source/#srcset

2024-11-28 20:10 UTC, Avaakum commented on index.html
> +      <source srcset="images/cards-1x.png" type="image/png">
Вместо этого тега <source> задайте атрибут srcset с этим значением сразу для тега  img вместо атрибута src

Тут так же стоит использовать srcset и указать 2 изображения в значении атрибута. Вместо последнего source и img, тогда будет только img c srcset  вместо src. На ошибку валидатора в данном случае можно не обращать внимание

---

А так же порядок форматов должен быть от самого прогрессивного и оптимизированного до самого старого формата. У тега img должны быть изображения png.

2024-11-28 20:10 UTC, Avaakum commented on index.html
> +  <figure class="content__figure">
---

**Отлично:**

Отличная семантика и структура

2024-11-28 20:10 UTC, Avaakum commented on index.html
> +      Strategies — тем более, что их моментально разбирают фанаты Ино. Есть довольно симпатичные веб-сайты с
Слово "веб-сайты" так же должно быть ссылкой из макета

2024-11-28 20:10 UTC, Avaakum commented on index.html
> +</head>
---

**Отлично:**

Корректно заполнен `head`

2024-11-29 07:45 UTC, dmitrykoryanov commented on styles/style.css
> +.header__theme-toggler {
Done.

2024-11-29 07:48 UTC, dmitrykoryanov commented on styles/style.css
> +.colored-text {
Done.

2024-11-29 07:49 UTC, dmitrykoryanov commented on styles/style.css
> +  font-family: var(--accent-font), sans-serif;
Done.

2024-11-29 07:50 UTC, dmitrykoryanov commented on styles/style.css
> +li::before {
Done.

2024-11-29 08:00 UTC, dmitrykoryanov commented on index.html
> +    <div class="header__logo">
Done.

2024-11-29 08:03 UTC, dmitrykoryanov commented on index.html
> +      <source srcset="images/cards-1x.avif" type="image/avif">
Done.

2024-11-29 08:06 UTC, dmitrykoryanov commented on index.html
> +      <source srcset="images/cards-1x.png" type="image/png">
Done.

2024-11-29 08:06 UTC, dmitrykoryanov commented on index.html
> +  <figure class="content__figure">
Ok.

2024-11-29 08:07 UTC, dmitrykoryanov commented on index.html
> +</head>
OK, не я заполнял, так уже было. :)

2024-11-29 08:12 UTC, dmitrykoryanov commented on index.html
> +      Strategies — тем более, что их моментально разбирают фанаты Ино. Есть довольно симпатичные веб-сайты с
Done.

2024-11-30 21:20 UTC, dmitrykoryanov commented
Большое спасибо за такое детальное и обстоятельное ревью, очень полезно.

2024-12-01 13:49 UTC, Avaakum approved these changes
Развернуть общий комментарий ⬇︎

Здравствуйте! Рад вам сообщить, что ваша работа принята. Сейчас страничка выглядит прекрасно, всё работает отлично. Отличная семантика и структура. Желаю вам удачи в следующих спринтах и проектах! 




Ссылки:

- Можно использовать неразрывные пробелы для того чтобы текст не переносился в неожиданных местах. Неразрывные пробелы заменяют обычные, если нужно чтобы какая-то фраза не переносилась, например не нужно чтобы "на собаках" раскидывалось по разным строчкам при некоторых ширинах экранов, тогда `«на&nbsp;собаках»`. Но если страница с адаптацией, то всегда стоит проверять как текст с пробелами выглядит на всех ширинах.
- Про альтернативный текст для картинок https://habr.com/ru/post/341810/
- [Ссылка про подгрузку шрифтов](https://only-to-top.ru/blog/tools/2019-03-13-nastrojte-pokaz-vsego-teksta-vo-vremya-zagruzki-veb-shriftov.html) 


Несколько  ссылок на материал по теме нативных CSS переменных от авторов практикума:

- [1 часть](https://tproger.ru/articles/custom-properties-in-css-part-1/)

- [2 часть](https://tproger.ru/articles/custom-properties-in-css-part-2/)

- [3 часть](https://tproger.ru/articles/custom-properties-in-css-part-3/)



**Hover и псевдоэлементы**

Псевдоэлементы:

- https://developer.mozilla.org/ru/docs/Web/CSS/Pseudo-elements
- https://habr.com/ru/post/154319/
-  https://webformyself.com/krutoe-ispolzovanie-psevdoelementov-css-before-i-after/
-  https://www.internet-technologies.ru/articles/5-priemov-css3-s-psevdoelementami-before-i-after.html

Hover:

- Базовая спека http://htmlbook.ru/css/hover		
- https://codepen.io/igosheva_nastya/pen/qeJmMM

**БЭМ**

- Соглашение по именованию БЭМ https://ru.bem.info/methodology/naming-convention/
- Часто используемые слова в классах https://github.com/yoksel/common-words
- Где описывать геометрию https://ru.bem.info/methodology/faq/#Зачем-внешнюю-геометрию-и-позиционирование-задавать-через-родительский-блок
- Проверить БЭМ валидатором https://nglazov.github.io/bem-validator-page/

** Доступность**

- https://medium.com/web-standards/what-accessibility-taught-me-207d1ff0e80c



**Игры по flex/grid**

- https://flexboxfroggy.com/#ru
- https://cssgridgarden.com/#ru




**Grid-layout**

- https://css-tricks.com/snippets/css/complete-guide-grid/ (en)
- https://tuhub.ru/posts/css-grid-complete-guide
- https://medium.com/@stasonmars/вёрстка-на-grid-в-css-полное-руководство-и-справочник-220508316f8b

2024-12-01 13:49 UTC, Avaakum commented on styles/style.css
> +.theme_dark .content-list li::before {
---

**Можно лучше:**

Вложенность селекторов должна быть не более двух, или при изменении страницы сложно будет за этим следить. Желательно задать класс для элементов и присваивать стили сразу классам вместо тегов.

По этому принципу желательно проверить и следующие селекторы

2025-01-23 11:16 UTC, merged